// Code generated by "stringer -type=MetricType"; DO NOT EDIT.

package metrics

import "fmt"

const _MetricType_name = "CounterMetricTypeTimerMetricType"

var _MetricType_index = [...]uint8{0, 17, 32}

func (i MetricType) String() string {
	if i < 0 || i >= MetricType(len(_MetricType_index)-1) {
		return fmt.Sprintf("MetricType(%d)", i)
	}
	return _MetricType_name[_MetricType_index[i]:_MetricType_index[i+1]]
}
